version: "3"

services:
  nodeodm:
    image: global_drones/nodeodm:gpu
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile.gpu
    expose:
      - "3000"
    restart: unless-stopped
    oom_score_adj: 500
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
